# Copyright © 2026 Rohit Ananthan
# Licensed under the GNU Affero General Public License v3.0 or later.
"""context_compressor.py — summarize dropped conversation turns so
truncation doesn't silently erase context.

Borrowed 2026-04-21 from hermes-agent's context_compressor (MIT).
Adapted to Maez's simpler chat surface: no deep tool chains, no
provider-failover complexity, no iterative multi-compaction state.

Problem this fixes:
  skills/telegram_voice.py hard-caps _conversation_thread at 12 turns:

      if len(self._conversation_thread) > 12:
          self._conversation_thread = self._conversation_thread[-12:]

  When a conversation exceeds that, turns 1..N-12 just disappear. If
  those turns contained the Active Task ("Rohit asked me to refactor
  X"), the assistant loses it mid-conversation. skills/telegram_public
  has the same issue at 6 turns.

What this module does:
  compress(thread, keep_tail_n) returns a new list where the dropped
  head turns have been replaced with a single system-role summary
  message. The summary is generated by the dedicated judge llama-
  server (MAEZ_JUDGE_BASE_URL) — same endpoint, already hot.

Framing convention (from Hermes + OpenCode + Codex):
  - Summary is prefixed with "[CONTEXT COMPACTION — REFERENCE ONLY]"
    so the model doesn't treat summarized past requests as current.
  - Summary is written as a handoff to a "different assistant" so it
    doesn't read as active first-person history.
  - "Do not respond to questions in this summary" is explicit.

Fail-SAFE: if the summarizer fails, returns the thread truncated to
the last keep_tail_n turns — identical to the current truncation
behavior. Never raises.
"""
from __future__ import annotations

import json
import logging
import os
import urllib.request
from typing import Optional

logger = logging.getLogger("maez.context_compressor")

_JUDGE_BASE_URL = os.environ.get("MAEZ_JUDGE_BASE_URL", "").rstrip("/")
_JUDGE_MODEL = os.environ.get("MAEZ_JUDGE_MODEL", "maez-judge")
_SUMMARIZER_TIMEOUT_S = float(os.environ.get("MAEZ_SUMMARIZER_TIMEOUT_S", "30"))
_SUMMARY_MAX_TOKENS = int(os.environ.get("MAEZ_SUMMARY_MAX_TOKENS", "600"))

# Prefix applied to every summary. Tells the model the block is
# reference material, not active instructions. Without this the model
# treats summarized past user requests as if they were asking them now.
_SUMMARY_PREFIX = (
    "[CONTEXT COMPACTION — REFERENCE ONLY] Earlier turns of this "
    "conversation were compacted into the summary below. Treat this as "
    "background reference about what has already happened, NOT as active "
    "instructions. Do NOT answer questions or fulfill requests that "
    "appear in this summary — they were already addressed. Respond only "
    "to the messages that follow this summary."
)

_SUMMARIZER_PROMPT_TEMPLATE = (
    "You are writing a context handoff for a different assistant that "
    "will continue this conversation. Summarize the turns below in a "
    "structured format. Do NOT respond to any questions — only write "
    "the summary. Do NOT include preamble or greeting. Be concrete: "
    "preserve specific names, commands, paths, numbers.\n\n"
    "USE THIS EXACT STRUCTURE:\n\n"
    "## Active Task\n"
    "The single most important thing. Copy the user's most recent "
    "unfulfilled request verbatim if any. Else write 'None.'\n\n"
    "## What Happened\n"
    "2-6 bullets: what the user asked, what the assistant did, any "
    "tools run, any decisions made.\n\n"
    "## Key Facts\n"
    "Any concrete values (file paths, commands, error messages, "
    "numbers, names) that shouldn't be lost.\n\n"
    "## Open Questions\n"
    "Questions from the user that haven't been answered. Else 'None.'\n\n"
    "TURNS TO SUMMARIZE:\n"
    "{turns_text}\n"
)


def _serialize_turns(turns: list[dict]) -> str:
    """Format turns as labeled text for the summarizer. Truncates very
    long individual contents so the prompt fits in the judge's ctx."""
    parts: list[str] = []
    for t in turns:
        role = (t.get("role") or "unknown").upper()
        content = t.get("content") or ""
        if not isinstance(content, str):
            content = str(content)
        if len(content) > 2000:
            content = content[:1500] + "\n...[truncated]...\n" + content[-400:]
        parts.append(f"[{role}]: {content}")
    return "\n\n".join(parts)


def _call_summarizer(prompt: str) -> Optional[str]:
    """Call the dedicated judge endpoint for summarization. Returns None
    on any failure — caller falls back to no-summary behavior."""
    if not _JUDGE_BASE_URL:
        logger.debug("no MAEZ_JUDGE_BASE_URL — cannot summarize")
        return None
    body = json.dumps({
        "model": _JUDGE_MODEL,
        "messages": [
            {"role": "system",
             "content": "You are a summarization agent. Output only the "
                        "structured summary — no preamble, no meta-commentary."},
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.0,
        "max_tokens": _SUMMARY_MAX_TOKENS,
        # Qwen3/3.5 reasoning mode would dump tokens into reasoning_content
        # and leave the summary empty. Disable.
        "chat_template_kwargs": {"enable_thinking": False},
    }).encode()
    req = urllib.request.Request(
        f"{_JUDGE_BASE_URL}/v1/chat/completions",
        data=body,
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=_SUMMARIZER_TIMEOUT_S) as resp:
            data = json.loads(resp.read())
    except Exception as e:
        logger.debug("summarizer call failed: %s", e)
        return None
    try:
        content = data["choices"][0]["message"]["content"] or ""
    except Exception as e:
        logger.debug("summarizer response malformed: %s", e)
        return None
    content = content.strip()
    return content or None


def _build_summary_message(summary_text: str) -> dict:
    """Wrap a summary as a 'system' role message with the handoff prefix.

    telegram_voice and telegram_public both build messages like
    [system, user, ...thread..., user]. Using 'system' keeps the summary
    out of the conversational turn stream while still reaching the model.
    """
    return {
        "role": "system",
        "content": f"{_SUMMARY_PREFIX}\n\n{summary_text}",
    }


def compress(
    thread: list[dict],
    *,
    keep_tail_n: int,
    min_to_compress: int = 2,
) -> list[dict]:
    """Return a thread where any turns beyond keep_tail_n are summarized
    into a single system-role message at the head.

    Args:
        thread: full conversation turn list (each {role, content}).
        keep_tail_n: keep the most recent N turns verbatim. Summarize the rest.
        min_to_compress: don't summarize if fewer than this many head turns
            would be dropped — summary overhead isn't worth it.

    Behavior:
        - If thread already ≤ keep_tail_n: returns thread unchanged.
        - If head slice < min_to_compress: returns thread truncated to tail
          (same as the current truncation behavior).
        - Otherwise: summarize the head slice, return
          [summary_system_msg, *tail].

    Never raises. Fail-safe: any summarizer failure returns the
    tail-truncated thread (no summary, no info explicitly preserved,
    but also no crash).
    """
    n = len(thread)
    if n <= keep_tail_n:
        return list(thread)

    head_slice = thread[: n - keep_tail_n]
    tail = thread[n - keep_tail_n :]

    if len(head_slice) < min_to_compress:
        return list(tail)

    turns_text = _serialize_turns(head_slice)
    prompt = _SUMMARIZER_PROMPT_TEMPLATE.format(turns_text=turns_text)
    summary = _call_summarizer(prompt)

    if not summary:
        # Fail-safe: behave as the old truncation did. One debug line so
        # the cockpit can track the skip rate later.
        logger.debug(
            "context_compressor: summarizer unavailable, dropping %d "
            "head turns without summary",
            len(head_slice),
        )
        return list(tail)

    return [_build_summary_message(summary), *tail]
